<div class="row">
    <div class="col-12">
        <?php if(!Session::getInstance()->isLoggedIn()): ?>
            <a href="<?php echo App::config("url")."admin/login" ?>">Login</a>
            <a href="<?php echo App::config("url")."admin/registration" ?>">Registration</a>
        <?php else: ?>
            <a href="<?php echo App::config("url")."admin/logout" ?>">Logout
                <?php echo  htmlspecialchars(Session::getInstance()->getUser()->firstname) ?></a>
            <a href="<?php echo App::config('url') . "admin/profile" ?>">Profile</a>
        <?php endif; ?>
    </div>
</div>


<div class="row">
    <div class="col-12">
        <?php if(Session::getInstance()->isLoggedIn()):?>
            <form method="post" action="<?php echo App::config('url') ?>Index/newPost">

                <div class="form-group">
                    <label for="content">What's on your mind?</label>
                    <input class="form-control" id="content" name="content" autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="tags">Tags</label>
                    <input type="text" name="tags" id="tags" class="form-control">
                </div>

                <button type="submit" class="btn btn-primary">Save</button>

            </form>
        <?php endif; ?>
        <hr />
    </div>
</div>


<div class="row">
    <?php foreach ($posts as $post): ?>
    <div class="col-12">
        <?php if ($post->getReports() >= 5): ?>
            <p>Post uklonjen.</p>
        <hr />
        <?php else: ?>
            <p>
                <cite><?= htmlspecialchars($post->getUser()) ?></cite>
                <?php echo $post->date ?>
                <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
                    <?= htmlspecialchars($post->getContent()) ?> </a> <br />
                <p>
                    <?php foreach ($post->getTags() as $tag): ?>
                        <small><?php echo $tag->name; ?></small>
                    <?php endforeach; ?>
                </p>
                <?php if( Session::getInstance()->isLoggedIn() ): ?>
                    <a href="<?php echo App::config('url') ?>Admin/like/<?php echo $post->id ?>">Like</a>
                <?php endif; ?>

                (<?php echo $post->getLikes() ?> likes)<br>
                <?php if( Session::getInstance()->isLoggedIn() ): ?>
                    <a href="<?php echo App::config('url') ?>Admin/reportPost/<?php echo $post->id ?>">Report</a>
                <?php endif; ?>
                (<?php echo $post->getReports() ?> reports)<br>

                <?php foreach ($post->getComments() as $comment): ?>
                <p style="margin-left: 20px;">
                    <cite><?= htmlspecialchars($comment->user) ?></cite>
                    <?php echo $comment->date ?><br />
                    <?php echo $comment->content ?>
                </p>

                <?php endforeach; ?>
            </p>
            <hr />
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>



<?php //echo password_hash("p", PASSWORD_DEFAULT);
