<div class="row">
    <div class="col-12">
        <?php if(!Session::getInstance()->isLoggedIn()): ?>
            <a href="<?php echo App::config("url")."admin/login" ?>">Login</a>
            <a href="<?php echo App::config("url")."admin/registration" ?>">Registration</a>
        <?php else: ?>
            <a href="<?php echo App::config("url")."admin/logout" ?>">Logout
                <?php echo  htmlspecialchars(Session::getInstance()->getUser()->firstname) ?></a>
            <a href="<?php echo App::config('url') . "admin/profile" ?>">Profile</a>
        <?php endif; ?>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <?php if(Session::getInstance()->isLoggedIn()):?>
            <form method="post" action="<?php echo App::config('url') ?>Index/newPost">

                <div class="form-group">
                    <label for="content">What's on your mind?</label>
                    <input class="form-control" id="content" name="content" autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="tags">Tagovi(u slučaju unosa više tagova odvojiti ih zarezom)</label>
                    <input type="text" name="tags" id="tags" class="form-control">
                </div>

                <button type="submit" class="btn btn-primary">Save</button>

            </form>
        <?php endif; ?>
        <hr />
    </div>
</div>

<?php
    if (Session::getInstance()->isLoggedIn()) {
        $id = Session::getInstance()->getUser()->id;
        $user = User::userData($id);
    }

    $postCount = Post::postCount();
    $totalPages = ceil($postCount/10);
?>
<div class="row">
    <div class="col-4 offset-4">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <?php for ($i=1;$i<=$totalPages;$i++): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?php echo App::config('url') ?>Index/pagination/<?php echo $i ?>"><?php echo $i ?></a>
                    </li>
                <?php endfor; ?>
            </ul>
        </nav>
    </div>
</div>
<?php foreach ($posts as $post): ?>
    <?php if ($post->getReports() < 5): ?>
        <div class="row">
            <div class="col-12 card">
                <div class="card-body">
                    <?php if (!$post->hidden && Session::getInstance()->isLoggedIn() && $user->getRole() === 'admin'): ?>
                        <a href="<?php echo App::config('url') ?>Admin/hide/<?php echo $post->id ?>">Ukloni</a>
                    <?php endif; ?>

                    <?php if ($post->hidden && Session::getInstance()->isLoggedIn() &&
                        Session::getInstance()->getUser()->id === $post->getUserid() ): ?>
                            <p><a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?>">Admin uklonio post</a></p>
                    <?php elseif (!$post->hidden && (!Session::getInstance()->isLoggedIn() || Session::getInstance()->isLoggedIn())): ?>
                        <p>
                            <cite><?= htmlspecialchars($post->getUser()) ?></cite>
                            <?php echo $post->date ?>
                            <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
                                <?= htmlspecialchars($post->getContent()) ?> </a> <br />
                            <p>
                                <?php foreach ($post->getTags() as $tag): ?>
                                    <small><?php echo $tag->name; ?></small>
                                <?php endforeach; ?>
                            </p>
                            <?php if( Session::getInstance()->isLoggedIn() ): ?>
                                <a href="<?php echo App::config('url') ?>Admin/like/<?php echo $post->id ?>">Like</a>
                            <?php endif; ?>

                            (<?php echo $post->getLikes() ?> likes)<br>
                            <?php if(Session::getInstance()->isLoggedIn() && Session::getInstance()->getUser()->id != $post->getUserid() ): ?>

                                <a href="<?php echo App::config('url') ?>Admin/reportPost/<?php echo $post->id ?>">Report</a>
                            <?php endif; ?>
                            (<?php echo $post->getReports() ?> reports)<br>
                            <p>Comments</p>
                            <?php foreach ($post->getComments() as $comment): ?>
                                <p style="margin-left: 20px;">
                                    <cite><?= htmlspecialchars($comment->user) ?></cite>
                                    <?php echo $comment->date ?><br />
                                    <?php echo $comment->content ?>
                                </p>
                            <?php endforeach; ?>
                        </p>

                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach; ?>

<div class="row">
    <div class="col-4 offset-4">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <?php for ($i=1;$i<=$totalPages;$i++): ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo App::config('url') ?>Index/pagination/<?php echo $i ?>"><?php echo $i ?></a>
                </li>
                <?php endfor; ?>
            </ul>
        </nav>
    </div>
</div>
<script>
    window.onload = function() {
        history.replaceState("", "", <?php App::config('url') ?>);
    }
</script>


<?php //echo password_hash("p", PASSWORD_DEFAULT);
