<div class="row">
    <div class="col-12">
        <a href="<?php echo App::config('url') ?>">Index</a>
    </div>
</div>
<div class="row">
    <?php if (!empty($message)): ?>
        <div class="col-4 offset-4">
            <p class="alert alert-info"><?php echo $message ?></p>
        </div>
    <?php endif; ?>
    <div class="col-12">
        <form method="post" action="<?php echo App::config('url') ?>admin/authorize">

            <div class="form-group">
                <label for="email">Email</label>
                <input class="form-control" type="email" name="email" id="email" placeholder="pperic@gmail.com">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input class="form-control" type="password" name="password" id="password" placeholder="p">
            </div>

            <button type="submit" class="btn btn-primary">Authorize</button>

        </form>
    </div>
</div>

