<?php
    $userid = Session::getInstance()->getUser()->id;
    $user = User::userData($userid);
?>
<div class="row">
    <div class="col-12">
        <a href="<?php echo App::config("url") ?>">Index</a>
        <hr />

    </div>
</div>
<div class="row">
    <?php if (!empty($message)): ?>
        <div class="col-4 offset-4">
            <p class="alert alert-info"><?php echo $message?></p>
        </div>
    <?php endif; ?>
</div>
<div class="row">
    <div class="col-4">

        <?php if ($user->getImage()): ?>
            <div class="card">
                <img class="card-img-top" src="<?php echo App::config("url") ?>uploads/<?php echo $user->getImage() ?>" alt="">
            </div>
        <?php else: ?>
        <div class="img-div">
            <img src="<?php echo App::config('url').'app/view/barcode.php?size=100&text='.$user->getFirstName() .
                $user->getEmail()?>">
        </div>
        <?php endif; ?>
        <form action="<?php echo App::config("url") ?>Admin/updateImage/<?php echo Session::getInstance()->getUser()->id ?>"
        method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="image">Change image</label>
                <input type="file" name="image" id="image">
            </div>
            <button type="submit" class="btn btn-primary">Change</button>
        </form>
    </div>
    <div class="col-4">
        <h3>User current info</h3>
        form
        <form action="<?php echo App::config("url") ?>Admin/updateUser/<?php echo Session::getInstance()->getUser()->id ?>"
        method="post">
            <div class="form-group">
                <label for="firstname">First name</label>
                <input class="form-control" type="text" name="firstname" id="firstname"
                value="<?php echo htmlspecialchars(Session::getInstance()->getUser()->firstname) ?>" autocomplete="off">
            </div>

            <div class="form-group">
                <label for="lastname">Last name</label>
                <input class="form-control" type="text" name="lastname" id="lastname"
                value="<?php echo htmlspecialchars(Session::getInstance()->getUser()->lastname) ?>" autocomplete="off">
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input class="form-control" type="email" name="email" id="email"
                value="<?php echo htmlspecialchars(Session::getInstance()->getUser()->email) ?>" autocomplete="off">
            </div>

            <input type="hidden" name="id" value="<?php echo Session::getInstance()->getUser()->id ?>">
            <button type="submit" class="btn btn-primary">Change</button>
        </form>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-4 offset-4">
        <h3>Change password</h3>
        <form action="<?php echo App::config("url") ?>Admin/updatePassword/<?php echo Session::getInstance()->getUser()->id ?>" 
        method="post">
            <div class="form group">
                <label for="newPassword">New password</label>
                <input class="form-control" type="password" name="newPassword" id="newPassword">
            </div>
            <div class="form-group">
                <label for="confPassword">Confrim password</label>
                <input class="form-control" type="password" name="confPassword" id="confPassword">
            </div>
            <button type="submit" class="btn btn-primary">Change</button>
        </form>
    </div>
</div>


