

<div class="row">
    <div class="col-12">
        <form method="post" action="<?php echo App::config('url') ?>admin/register">

            <div class="form-group">
                <label for="firstname">First name</label>
                <input class="form-control" type="text" name="firstname" id="firstname">
            </div>

            <div class="form-group">
                <label for="lastname">Last name</label>
                <input class="form-control" type="text" name="lastname" id="lastname">
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input class="form-control" type="email" name="email" id="email">
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input class="form-control" type="password" name="pass" id="password">
            </div>

            <button type="submit" class="btn btn-primary">Register</button>

        </form>
    </div>
</div>

