<div class="row">
    <div class="col-12">
        <a href="<?php echo App::config("url") ?>">Index</a><hr />
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php if( Session::getInstance()->isLoggedIn() &&
            $post->getUserid()==Session::getInstance()->getUser()->id): ?>
            <a href="<?php echo App::config("url") ?>admin/delete/<?php echo $post->getId() ?>">Delete posts (and all likes and comments</a><br />
        <?php endif; ?>
    </div>
    <div class="col-12">
        <cite><?= htmlspecialchars($post->getUser()) ?></cite>  <?php echo $post->date ?>
        <p><?= htmlspecialchars($post->getContent()) ?>
        <p>
            <?php foreach ($post->getTags() as $tag): ?>
                <small><?= htmlspecialchars($tag->name) ?></small>
            <?php endforeach; ?>
        </p>

        </p>
        <span>
            Reports: <?php echo $post->getReports() ?> ||
            Likes: <?php echo $post->getLikes() ?>
        </span>

    </div>
    <div class="col-12">
        <h3>Comments</h3>
    </div>
</div>

<div class="row">
    <?php foreach ($post->getComments() as $comment): ?>
    <div class="col-12">

        <p>
            <cite><?= htmlspecialchars($comment->user) ?></cite>
            <?php echo htmlspecialchars($comment->date) ?><br />
            <?php echo htmlspecialchars($comment->content) ?>
        </p>
    </div>

    <?php endforeach; ?>
</div>


<?php if( Session::getInstance()->isLoggedIn() ): ?>
<div class="row">
    <div class="col-12">
        <form method="post" action="<?php echo App::config('url') ?>admin/comment/<?php echo $post->getId() ?>">

            <div class="form-group">
                <label for="content">New comment</label>
                <input class="form-control" id="content" name="content">
            </div>

            <button type="submit" class="btn btn-primary">Save</button>

        </form>
    </div>
</div>

<?php endif; ?>